### PR TITLE
Spree v4.5 support

### PR DESCRIPTION
**Pull request by mrbrdo**
I have merged some old pull requests and added a few of my own commits to make this work on Spree v4.5.

### CODE REVIEW

**Comment by rafalcymerys** [comment]
Hi @mrbrdo great timing, we were just reviewing spree-contrib gems and making adjustments for Rails 7/Spree 4.5 :D 
Does this PR also include some other PRs that you've created before? Just trying to understand the scope of changes.

**Comment by mrbrdo** [comment]
@rafalcymerys it doesn't include any prior code of mine, only pull requests from the repo or commits from forks I found in the Github network tab. I only first looked at this gem a few days ago.
Btw as mentioned, there is still some code related to this gem inside spree core and spree_legacy_frontend.

**Comment by SylarRuby** [comment]
Bump. Would love to use this and yes, some references are there for spree_legacy_frontend.

**Comment by mrbrdo** [comment]
Although not directly related, I just want to note that since Rails 7, it seems [double quotes are the norm now](https://github.com/rails/rails/pull/42064). So the houndci-bot rules should probably be updated regarding Style/StringLiterals.

**Comment by damianlegawiec** [comment]
Thanks @mrbrdo 👍 

I'll merge this PR as it is right now, it will require more work to fit into newer Spree versions and new admin/storefront, also setting up proper CI and removing Hound (we don't use that anymore, just standard rubocop)

**Pull request merged**
